document.write('<div class="rom-btm">');
document.write('              <div class="col-md-3 room-left wow fadeInLeft animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInLeft;">');
document.write('                <img src="paris.jpg" class="img-responsive" alt="">');
document.write('              </div>');
document.write('              <div class="col-md-6 room-midle wow fadeInUp animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">');
document.write('                <h4>Package Name: Swiss Paris Delight Premium 2020 (Group Package)</h4>');
document.write('                <h6>Package Type : Group Package</h6>');
document.write('                <p><b>Package Location :</b> Paris and Switzerland</p>');
document.write('                <p><b>Features</b> Round trip Economy class airfare valid for the duration of the holiday - Airport taxes - Accommodation for 3 nights in Paris and 3 nights in scenic Switzerland - Enjoy continental breakfasts every morning - Enjoy 5 Indian dinners in Mainland Europe - Exp</p>');
document.write('              </div>');
document.write('              <div class="col-md-3 room-right wow fadeInRight animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInRight;">');
document.write('                <h5>USD 8000</h5>');
document.write('                <a href="package-details.php?pkgid=1" class="view">Details</a>');
document.write('              </div>');
document.write('              <div class="clearfix"></div>');
document.write('            </div>');

document.write('<div class="rom-btm">');
document.write('              <div class="col-md-3 room-left wow fadeInLeft animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInLeft;">');
document.write('                <img src="sydney.jpg" class="img-responsive" alt="">');
document.write('              </div>');
document.write('              <div class="col-md-6 room-midle wow fadeInUp animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;">');
document.write('                <h4>Package Name: Australia Delight Premium 2020 (Group Package)</h4>');
document.write('                <h6>Package Type : Group Package</h6>');
document.write('                <p><b>Package Location :</b> Sydney and Melborne</p>');
document.write('                <p><b>Features</b> Round trip Economy class airfare valid for the duration of the holiday - Airport taxes - Accommodation for 3 nights in Paris and 3 nights in scenic Switzerland - Enjoy continental breakfasts every morning - Enjoy 5 Indian dinners in Mainland Europe - Exp</p>');
document.write('              </div>');
document.write('              <div class="col-md-3 room-right wow fadeInRight animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInRight;">');
document.write('                <h5>USD 5000</h5>');
document.write('                <a href="package-details.php?pkgid=1" class="view">Details</a>');
document.write('              </div>');
document.write('              <div class="clearfix"></div>');
document.write('            </div>');